+incdir+./rtl/inc

./rtl/cekirdek/yurut/toplayici/black.v
./rtl/cekirdek/yurut/carp.v
./rtl/cekirdek/yurut/carry_less_multiply.v
./rtl/cekirdek/yurut/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v
./rtl/cekirdek/yurut/toplayici/grey.v
./rtl/cekirdek/yurut/toplayici/ks_1.v
./rtl/cekirdek/yurut/toplayici/ks_2.v
./rtl/cekirdek/yurut/toplayici/ks_3.v
./rtl/cekirdek/yurut/toplayici/ks_4.v
./rtl/cekirdek/yurut/toplayici/ks_5.v
./rtl/cekirdek/yurut/toplayici/ks_6.v
./rtl/cekirdek/yurut/toplayici/ks_7.v
./rtl/cekirdek/yurut/toplayici/ksa_top.v
./rtl/bellek/l1b_denetleyici.v
./rtl/cekirdek/yurut/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v
./rtl/cekirdek/yurut/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v
./rtl/cekirdek/yurut/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v
./rtl/cekirdek/yurut/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v
./rtl/cekirdek/yurut/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v
./rtl/cekirdek/yurut/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v
./rtl/cekirdek/yurut/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v
./rtl/cekirdek/yurut/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v
./rtl/cekirdek/yurut/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v
./rtl/cekirdek/yurut/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v
./rtl/cekirdek/yurut/cvfpu/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v
./rtl/bellek/pdk_sram.v
./rtl/cekirdek/yurut/toplayici/pg.v
./rtl/uart/t_fifo.v
./rtl/cekirdek/yurut/ts_bolucu.v
./rtl/uart/uart_alici.v
./rtl/uart/uart_kontrolcu.v
./rtl/uart/uart_verici.v
./rtl/veriyolu/veriyolu.v
./rtl/cekirdek/pkgs/riscv_instr.sv
./rtl/cekirdek/yurut/cvfpu/src/fpnew_pkg.sv
./rtl/cekirdek/pkgs/yurut_pkg.sv
./rtl/cekirdek/pkgs/sabitler_pkg.sv
./rtl/cekirdek/pkgs/coz_pkg.sv
./rtl/cekirdek/yurut/abib.sv
./rtl/cekirdek/yurut/cvfpu/src/common_cells/src/cf_math_pkg.sv
./rtl/cekirdek/pkgs/csr_pkg.sv
./rtl/cekirdek.sv
./rtl/cekirdek/yurut/cvfpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
./rtl/cekirdek/yurut/cvfpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
./rtl/cekirdek/coz_yazmacoku.sv
./rtl/cekirdek/csr.sv
./rtl/cekirdek/yurut/cvfpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
./rtl/cekirdek/yurut/cvfpu/src/fpnew_cast_multi.sv
./rtl/cekirdek/yurut/cvfpu/src/fpnew_classifier.sv
./rtl/cekirdek/yurut/cvfpu/src/fpnew_divsqrt_multi.sv
./rtl/cekirdek/yurut/cvfpu/src/fpnew_divsqrt_th_32.sv
./rtl/cekirdek/yurut/cvfpu/src/fpnew_fma.sv
./rtl/cekirdek/yurut/cvfpu/src/fpnew_fma_multi.sv
./rtl/cekirdek/yurut/cvfpu/src/fpnew_noncomp.sv
./rtl/cekirdek/yurut/cvfpu/src/fpnew_opgroup_block.sv
./rtl/cekirdek/yurut/cvfpu/src/fpnew_opgroup_fmt_slice.sv
./rtl/cekirdek/yurut/cvfpu/src/fpnew_opgroup_multifmt_slice.sv
./rtl/cekirdek/yurut/cvfpu/src/fpnew_rounding.sv
./rtl/cekirdek/yurut/cvfpu/src/fpnew_top.sv
./rtl/cekirdek/geri_yaz.sv
./rtl/cekirdek/pkgs/oncoz_pkg.sv
./rtl/cekirdek/getir.sv
./rtl/cekirdek/gshare.sv
./rtl/cekirdek/yurut/cvfpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
./rtl/bellek/l1v_denetleyici.sv
./rtl/cekirdek/yurut/cvfpu/src/common_cells/src/lzc.sv
./rtl/cekirdek/yurut/muib.sv
./rtl/cekirdek/yurut/cvfpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
./rtl/cekirdek/yurut/cvfpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
./rtl/cekirdek/oncozucu.sv
./rtl/cekirdek/yurut/cvfpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
./rtl/teknofest/programmer.sv
./rtl/cekirdek/ps_olustur.sv
./rtl/cekirdek/yurut/cvfpu/src/common_cells/src/rr_arb_tree.sv
./rtl/cekirdek/tehlike_birimi.sv
./rtl/teknofest/teknofest_memory.sv
./rtl/cekirdek/yurut/toprak_amb.sv
./rtl/veriyolu/wb_master.sv
./rtl/cekirdek/yazmac_obegi.sv
./rtl/yonga.sv
./rtl/cekirdek/yurut.sv
./rtl/cekirdek/yurut/zba_zbc_zbs.sv
./rtl/cekirdek/yurut/zbb.sv
./rtl/teknofest/teknofest_wrapper.sv
